language: python

python:
  - "3.6"

cache: pip

install:
  - pip install --upgrade setuptools==70.0.0
  - pip install -e .[ci]


script:
  - pytest --cov --cov-report term-missing:skip-covered

after_success:
  - coveralls
