language: python

python:
  - "3.6"

cache: pip

install:
  - pip install --upgrade setuptoolssetuptools~=74.1.1
  - pip install --upgrade packaging~=24.1
  - pip install -e .[ci]


script:
  - pytest --cov --cov-report term-missing:skip-covered

after_success:
  - coveralls
