name='ABRSQOL' 
version="0.1.0"
description='Numerical solution algorithm to invert a quality of life measure.'
# long_description=long_description,
# long_description_content_type='text/markdown',
url='https://github.com/Ahlfeldt/ABRSQOL-toolkit/blob/main/Python'
author='Gabriel M Ahlfeldt'
author_email='g.ahlfeldt@hu-berlin.de'
license='MIT'
